### ISSUE TITLE
CUDA is not available

### ISSUE THREAD

**Issue by seth33-J** [jones-lab-tamu/CBASv2#5]
Spawning Python: "C:\Users\hung\Desktop\CBAS\software\v3\CBAS\venv\Scripts\python.exe" -u C:\Users\hung\Desktop\CBAS\software\v3\CBAS\backend\app.py
[Python]: --- PyTorch GPU Diagnostics ---
CUDA available: False
PyTorch cannot find a CUDA-enabled GPU.

Thank you

**Comment by jones-lab-tamu** [comment]
Hi 

I think this may have also failed because you used 3.13 and you didn't reinstall.  Could you try completely uninstalling Python 3.13 from your system, installing the 64-bit version of 3.11 here [https://www.python.org/downloads/release/python-3119/](https://www.google.com/url?sa=E&q=https%3A%2F%2Fwww.python.org%2Fdownloads%2Frelease%2Fpython-3119%2F) (and click Add python.exe to PATH), delete the venv folder from your CBAS directory, and try to install again?

**Comment by seth33-J** [comment]
Yes, I reinstall everything and it works now. Thank you
